import Head from "next/head";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";

export const Container = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: blueviolet;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>#$!@#%@</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
